# DO NOT USE THIS FILE AS-IS FOR YOUR INITIAL CONFIGURATION
# ONLY TAKE THE SPECIFIC SECTION YOU WANT TO CONFIGURE
#
# For more information about configuration, visit https://github.com/kamax-io/mxisd/blob/master/docs/configure.md

spring:
  main:
    banner-mode: 'off'

logging:
  level:
    org:
      springframework: 'WARN'
      apache:
        catalina: 'WARN'
        directory: 'WARN'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} [%15.15t] %35.35logger{34} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

server:
  port: 8090

matrix:
  domain: ''
  identity:
    servers:
      root:
        - 'https://matrix.org'
  listener:
      url:  ''
      localpart: ''
      token:
        as: ''
        hs: ''

lookup:
  recursive:
    enabled: true
    allowedCidr:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '::1/128'

    bridge:
      enabled: false
      recursiveOnly: true

rest:
  endpoints:
    auth: '/_mxisd/backend/api/v1/auth/login'
    directory: '/_mxisd/backend/api/v1/directory/user/search'
    identity:
      single: '/_mxisd/backend/api/v1/identity/lookup/single'
      bulk: '/_mxisd/backend/api/v1/identity/lookup/bulk'

ldap:
  enabled: false
  filter: ''
  connection:
    host: ''
    tls: false
    port: 389
    bindDn: ''
    bindPassword: ''
    baseDn: ''
  attribute:
    uid:
      type: 'uid'
      value: 'userPrincipalName'
    name: 'displayName'
    threepid:
      email:
        - 'mailPrimaryAddress'
        - 'mail'
        - 'otherMailbox'
      msisdn:
        - 'telephoneNumber'
        - 'mobile'
        - 'homePhone'
        - 'otherTelephone'
        - 'otherMobile'
        - 'otherHomePhone'
  auth:
    filter: ''
  directory:
    attribute:
      other: []
    filter: ''
  identity:
    filter: ''
    token: '%3pid'
    medium:
      email: ''
      msisdn: ''

netiq:
  enabled: false
  filter: ''
  connection:
    host: ''
    tls: false
    port: 389
    bindDn: ''
    bindPassword: ''
    baseDn: ''
  attribute:
    uid:
      type: 'uid'
      value: 'userPrincipalName'
    name: 'displayName'
    threepid:
      email:
        - 'mailPrimaryAddress'
        - 'mail'
        - 'otherMailbox'
      msisdn:
        - 'telephoneNumber'
        - 'mobile'
        - 'homePhone'
        - 'otherTelephone'
        - 'otherMobile'
        - 'otherHomePhone'
  auth:
    filter: ''
  directory:
    attribute:
      other: []
    filter: ''
  identity:
    filter: ''
    token: '%3pid'
    medium:
      email: ''
      msisdn: ''

firebase:
  enabled: false


sql:
  enabled: false
  type: 'sqlite'
  connection: ''
  auth:
    enabled: false
  directory:
    enabled: false
    query:
      name:
        type: 'localpart'
        value: 'SELECT 1'
      threepid:
        type: 'localpart'
        value: 'SELECT 1'
  identity:
    type: 'mxid'
    query: 'SELECT user_id AS uid FROM user_threepids WHERE medium = ? AND address = ?'
  profile:
    threepid:
      query: 'SELECT medium, address FROM user_threepids WHERE user_id = ?'

synapseSql:
  enabled: false
  type: 'sqlite'
  profile:
      threepid:
        query: 'SELECT medium, address FROM user_threepids WHERE user_id = ?'

forward:
  servers:
    - 'https://matrix.org'
    - 'https://vector.im'

threepid:
  medium:
    email:
      identity:
        from: ''
        name: ''
      connector: 'smtp'
      generator: 'template'
      connectors:
        smtp:
          host: ''
          port: 587
          tls: 1
          login: ''
          password: ''
      generators:
        template:
          invite: 'classpath:threepids/email/invite-template.eml'
          inviteByMxid: 'classpath:threepids/email/invite-mxid-template.eml'
          session:
            validation:
              local: 'classpath:threepids/email/validate-local-template.eml'
              remote: 'classpath:threepids/email/validate-remote-template.eml'

    msisdn:
      connector: 'twilio'
      generator: 'template'
      connectors:
        twilio:
          accountSid: ''
          authToken: ''
          number: ''
      generators:
        template:
          invite: 'classpath:threepids/sms/invite-template.txt'
          inviteByMxid: 'classpath:threepids/sms/invite-mxid-template.txt'
          session:
            validation:
              local: 'classpath:threepids/sms/validate-local-template.txt'
              remote: 'classpath:threepids/sms/validate-remote-template.txt'

session:
  policy:
    validation:
      enabled: true
      forLocal:
        enabled: true
        toLocal: true
        toRemote:
          enabled: true
          server: 'root'
      forRemote:
        enabled: true
        toLocal: false
        toRemote:
          enabled: true
          server: 'root'

notification:
#  handler:
#    3PID-medium: 'handlerId'
  handlers:
    sendgrid:
      api:
        key: ''
      identity:
        from: ''
        name: ''
      templates:
        invite:
          subject: ''
          body:
            text: ''
            html: ''
        session:
          validation:
            local:
              subject: ''
              body:
                text: ''
                html: ''
            remote:
              subject: ''
              body:
                text: ''
                html: ''

view:
  session:
    local:
      onTokenSubmit:
        success: 'session/local/tokenSubmitSuccess'
        failure: 'session/local/tokenSubmitFailure'
    localRemote:
      onTokenSubmit:
        success: 'session/localRemote/tokenSubmitSuccess'
        failure: 'session/local/tokenSubmitFailure'
    remote:
      onRequest:
        success: 'session/remote/requestSuccess'
        failure: 'session/remote/requestFailure'
      onCheck:
        success: 'session/remote/checkSuccess'
        failure: 'session/remote/checkFailure'

invite:
  resolution:
    recursive: true
    timer: 1

storage:
  backend: 'sqlite'

directory:
  exclude:
    homeserver: false

---
spring:
  profiles: systemd

logging:
  pattern:
    console: '%d{.SSS} ${LOG_LEVEL_PATTERN:%5p} [%15.15t] %35.35logger{34} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
